-- H2-compatible schema for testing (no vector type, no JSONB — use TEXT)
CREATE TABLE IF NOT EXISTS kb_documents (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_type    VARCHAR(50)  NOT NULL,
    content     CLOB         NOT NULL,
    metadata    CLOB,
    embedding   CLOB,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
